/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface TimelineFilter {
    'config': object;
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface TimelineFilterAttributes extends StencilHTMLAttributes {
    'config'?: object;
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'TimelineFilter': Components.TimelineFilter;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'timeline-filter': Components.TimelineFilterAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLTimelineFilterElement extends Components.TimelineFilter, HTMLStencilElement {}
  var HTMLTimelineFilterElement: {
    prototype: HTMLTimelineFilterElement;
    new (): HTMLTimelineFilterElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'timeline-filter': HTMLTimelineFilterElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'timeline-filter': HTMLTimelineFilterElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
